### ISSUE TITLE
generated model architype doesn't work under eclipse for windows

### ISSUE THREAD

**Issue by lavecchi** [psibre/artimate#1]

**Comment by psibre** [comment]
It seems that the m2e plugin mangles the

``` xml
<parent>
  <relativePath>..</relativePath>
</parent>
```

in the archetype resources by appending the POM itself when the archetype is generated using Eclipse/m2e:

``` xml
<parent>
  <relativePath>../pom.xml</relativePath>
</parent>
```

This of course breaks any paths which might depend on the `${project.parent.relativePath}` property.

Since this issue isn't specific to Windows, we can assume it's a m2e bug. If someone has time to document this with a MWE, one should file a bug report for m2e.
